# Generated by Django 3.2.9 on 2024-01-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='objective_name',
            field=models.CharField(default='default value', max_length=200),
        ),
    ]
